### ISSUE TITLE
Build error: " `this` has been rewritten to `undefined` "

### ISSUE THREAD

**Issue by dmitry-kurmanov** [sveltejs/component-template#17] opened 2019-11-16 15:12 UTC
Hello! I've cloned the repo, run `npm i` and then saw the error:

"`this` has been rewritten to `undefined`"

accrording to the "Rollup" doc https://rollupjs.org/guide/en/#error-this-is-undefined we can use the `options.context` and `options.moduleContext`.

Should we set those options ?

**Comment by dmitry-kurmanov** [comment] 2019-11-16 15:57
for example @YogliB's tempalte [repo ](https://github.com/YogliB/svelte-component-template)`dev` script doesn't show the error

**Comment by antony** [comment] 2021-11-11 23:31
closing due to age. If this error still occurs, please provide a reproduction and we can look into it.

**Closed as completed by antony** 2021-11-11 23:31 UTC
